#!/bin/sh

PREFIX=""
FILE_LIST=""

while getopts "p:l:" opt; do
    case "$opt" in
        p) PREFIX="$OPTARG";;
        l) FILE_LIST="$OPTARG";;
    esac
done

shift "$((OPTIND - 1))"

if [ "x$1" != "x" ]; then
    DEST="$1"
    if [ "x$FILE_LIST" = "x" ]; then
        FILE_LIST="$DEST/dotfiles.list"
    fi
else
    echo "Error: No destination directory specified."
    exit 1
fi

for i in $(cat "$FILE_LIST"); do
    cp --recursive --parents "$PREFIX$i" "$DEST"
done
